USE web;

INSERT INTO categories (category_name) VALUES
('Kính cận'),
('Kính mát'),
('Kính áp tròng'),
('Gọng kính');

INSERT INTO	attributes (attribute_name) VALUES
('Giới tính'),
('Kiểu dáng'),
('Màu kính'),
('Màu áp tròng'),
('Chất liệu');

INSERT INTO	attribute_values (attribute_id, name_value) VALUES
-- Giới tính
(1, N'Nam'),
(1, N'Nữ'),

-- Kiểu dáng
(2, N'Vuông'),
(2, N'Tròn'),
(2, N'Oval'),
(2, N'Mắt mèo'),

-- Độ cận ko thể chèn
-- Màu kính
(3, N'Đen'),
(3, N'Nâu'),
(3, N'Xám'),

-- Màu áp tròng
(4, N'Trắng'),
(4, N'Xanh'),
(4, N'Đỏ'),
(4, N'Vàng'),

-- Chất liệu
(5, N'Kim loại'),
(5, N'Nhựa'),
(5, N'Titan');

INSERT INTO	attribute_values (attribute_id, category_id) VALUES
(1, 1), -- Kính cận - Giới tính
(1, 2), -- Kính cận - Kiểu dáng

(2, 1), -- Kính mát - Giới tính
(2, 2), -- Kính mát - Kiểu dáng
(2, 3), -- Kính mát - Màu kính

(3, 4), -- Kính áp tròng - Màu kính

(4, 2), -- Gọng kính - Màu kính
(4, 5); -- Gọng kính - Chất liệu


-- ================= KÍNH CẬN =================
INSERT INTO products
(category_id, product_name, brand, price, stock,
 short_infor_decription, short_guarantee_decription,
 general_description, shipping_info, product_details,
 glass_details, sold_quantity, created_at)
VALUES
-- Kính cận 10 sản phẩm
(1,'Kính cận AirFlex Nhẹ Pro','AirFlex',1200000,50,
'Thông tin sản phẩm\nChất liệu: Nhựa dẻo + Kim loại\nThương hiệu: AirFlex\nKích thước: 52-18-140\nTrọng lượng nhẹ, đeo lâu không đau tai',
'Bao gồm\nBảo hành 365 ngày\nĐổi trả trong 30 ngày\nTặng hộp đựng + khăn lau + Nước lau kính',
'Mô tả sản phẩm\nThể hiện sự trẻ trung với kính gọng đen AirFlex. Làm từ chất liệu cao cấp TR90, mềm mại và nhẹ nhàng giúp đeo lâu không mỏi. Thiết kế cổ điển mang đến phong cách thời trang và phù hợp với nhiều khuôn mặt.',
'Giao hàng từ 2–5 ngày tùy khu vực. Hỗ trợ đổi trả trong vòng 30 ngày.',
'Chi tiết sản phẩm\nMã sản phẩm: AFN548130-01\nCân nặng: 19.1g\nHình dạng: Quảng trường\nChiều rộng khung: 131mm\nKích cỡ: Trung bình\nPhù hợp khuôn mặt: Phổ biến\nVật liệu: TR90\nChiều rộng ống kính: 54mm\nChiều cao ống kính: 45mm\nChiều dài càng: 143mm',
'Chặn ánh sáng xanh\nGiảm mỏi mắt và bảo vệ mắt khỏi ánh sáng xanh có hại từ màn hình & thiết bị kỹ thuật số.\n\nQuang sắc\nTự động điều chỉnh theo ánh sáng, mang lại sự thoải mái cả ngày.\n\nPhân cực\nGiảm chói, tăng độ nét và bảo vệ mắt khỏi bề mặt phản chiếu.\n\nLái xe\nTăng độ tương phản để lái xe an toàn hơn.\n\nMàu nhuộm\nGiảm độ chói và mang lại độ rõ nét tốt hơn trong nhiều điều kiện ánh sáng.',
120,NOW()),
(1,'Kính cận AirFlex Chống Ánh Sáng Xanh','AirFlex',1350000,40,
'Thông tin sản phẩm\nChất liệu: Nhựa dẻo + Kim loại\nThương hiệu: AirFlex\nKích thước: 52-18-140\nTrọng lượng nhẹ, đeo lâu không đau tai',
'Bao gồm\nBảo hành 365 ngày\nĐổi trả trong 30 ngày\nTặng hộp đựng + khăn lau + Nước lau kính',
'Mô tả sản phẩm\nThể hiện sự trẻ trung với kính gọng đen AirFlex. Làm từ chất liệu cao cấp TR90, mềm mại và nhẹ nhàng giúp đeo lâu không mỏi. Thiết kế cổ điển mang đến phong cách thời trang và phù hợp với nhiều khuôn mặt.',
'Giao hàng từ 2–5 ngày tùy khu vực. Hỗ trợ đổi trả trong vòng 30 ngày.',
'Chi tiết sản phẩm\nMã sản phẩm: AFCSX548130-02\nCân nặng: 19.1g\nHình dạng: Quảng trường\nChiều rộng khung: 131mm\nKích cỡ: Trung bình\nPhù hợp khuôn mặt: Phổ biến\nVật liệu: TR90\nChiều rộng ống kính: 54mm\nChiều cao ống kính: 45mm\nChiều dài càng: 143mm',
'Chặn ánh sáng xanh\nGiảm mỏi mắt và bảo vệ mắt khỏi ánh sáng xanh có hại từ màn hình & thiết bị kỹ thuật số.\n\nQuang sắc\nTự động điều chỉnh theo ánh sáng, mang lại sự thoải mái cả ngày.\n\nPhân cực\nGiảm chói, tăng độ nét và bảo vệ mắt khỏi bề mặt phản chiếu.\n\nLái xe\nTăng độ tương phản để lái xe an toàn hơn.\n\nMàu nhuộm\nGiảm độ chói và mang lại độ rõ nét tốt hơn trong nhiều điều kiện ánh sáng.',
95,NOW()),
(1,'Kính cận Classic Phong Cách Cổ','Classic',900000,60,
'Thông tin sản phẩm\nChất liệu: Nhựa dẻo + Kim loại\nThương hiệu: Classic\nKích thước: 52-18-140\nTrọng lượng nhẹ, đeo lâu không đau tai',
'Bao gồm\nBảo hành 365 ngày\nĐổi trả trong 30 ngày\nTặng hộp đựng + khăn lau + Nước lau kính',
'Mô tả sản phẩm\nThể hiện phong cách cổ điển với kính Classic. Chất liệu TR90 mềm mại, nhẹ nhàng giúp đeo lâu không mỏi. Thiết kế tinh tế phù hợp nhiều khuôn mặt.',
'Giao hàng từ 2–5 ngày tùy khu vực. Hỗ trợ đổi trả trong vòng 30 ngày.',
'Chi tiết sản phẩm\nMã sản phẩm: CC548130-03\nCân nặng: 19.1g\nHình dạng: Quảng trường\nChiều rộng khung: 131mm\nKích cỡ: Trung bình\nPhù hợp khuôn mặt: Phổ biến\nVật liệu: TR90\nChiều rộng ống kính: 54mm\nChiều cao ống kính: 45mm\nChiều dài càng: 143mm',
'Chặn ánh sáng xanh\nGiảm mỏi mắt và bảo vệ mắt khỏi ánh sáng xanh có hại từ màn hình & thiết bị kỹ thuật số.\n\nQuang sắc\nTự động điều chỉnh theo ánh sáng, mang lại sự thoải mái cả ngày.\n\nPhân cực\nGiảm chói, tăng độ nét và bảo vệ mắt khỏi bề mặt phản chiếu.\n\nLái xe\nTăng độ tương phản để lái xe an toàn hơn.\n\nMàu nhuộm\nGiảm độ chói và mang lại độ rõ nét tốt hơn trong nhiều điều kiện ánh sáng.',
150,NOW()),
(1,'Kính cận Classic Thanh Lịch','Classic',950000,55,
'Thông tin sản phẩm\nChất liệu: Nhựa dẻo + Kim loại\nThương hiệu: Classic\nKích thước: 52-18-140\nTrọng lượng nhẹ, đeo lâu không đau tai',
'Bao gồm\nBảo hành 365 ngày\nĐổi trả trong 30 ngày\nTặng hộp đựng + khăn lau + Nước lau kính',
'Mô tả sản phẩm\nThể hiện phong cách thanh lịch với kính Classic. Chất liệu TR90 nhẹ nhàng, đeo lâu không mỏi. Thiết kế phù hợp nhiều khuôn mặt.',
'Giao hàng từ 2–5 ngày tùy khu vực. Hỗ trợ đổi trả trong vòng 30 ngày.',
'Chi tiết sản phẩm\nMã sản phẩm: CC548130-04\nCân nặng: 19.1g\nHình dạng: Quảng trường\nChiều rộng khung: 131mm\nKích cỡ: Trung bình\nPhù hợp khuôn mặt: Phổ biến\nVật liệu: TR90\nChiều rộng ống kính: 54mm\nChiều cao ống kính: 45mm\nChiều dài càng: 143mm',
'Chặn ánh sáng xanh\nGiảm mỏi mắt và bảo vệ mắt khỏi ánh sáng xanh có hại từ màn hình & thiết bị kỹ thuật số.\n\nQuang sắc\nTự động điều chỉnh theo ánh sáng, mang lại sự thoải mái cả ngày.\n\nPhân cực\nGiảm chói, tăng độ nét và bảo vệ mắt khỏi bề mặt phản chiếu.\n\nLái xe\nTăng độ tương phản để lái xe an toàn hơn.\n\nMàu nhuộm\nGiảm độ chói và mang lại độ rõ nét tốt hơn trong nhiều điều kiện ánh sáng.',
110,NOW()),
(1,'Kính cận Vision Titan Cao Cấp','Vision',1600000,30,
'Thông tin sản phẩm\nChất liệu: Nhựa dẻo + Kim loại\nThương hiệu: Vision\nKích thước: 52-18-140\nTrọng lượng nhẹ, đeo lâu không đau tai',
'Bao gồm\nBảo hành 365 ngày\nĐổi trả trong 30 ngày\nTặng hộp đựng + khăn lau + Nước lau kính',
'Mô tả sản phẩm\nKính Vision Titan cao cấp, TR90 mềm mại, nhẹ nhàng giúp đeo lâu. Phong cách sang trọng, phù hợp nhiều khuôn mặt.',
'Giao hàng từ 2–5 ngày tùy khu vực. Hỗ trợ đổi trả trong vòng 30 ngày.',
'Chi tiết sản phẩm\nMã sản phẩm: VT548130-05\nCân nặng: 19.1g\nHình dạng: Quảng trường\nChiều rộng khung: 131mm\nKích cỡ: Trung bình\nPhù hợp khuôn mặt: Phổ biến\nVật liệu: TR90\nChiều rộng ống kính: 54mm\nChiều cao ống kính: 45mm\nChiều dài càng: 143mm',
'Chặn ánh sáng xanh\nGiảm mỏi mắt và bảo vệ mắt khỏi ánh sáng xanh có hại từ màn hình & thiết bị kỹ thuật số.\n\nQuang sắc\nTự động điều chỉnh theo ánh sáng, mang lại sự thoải mái cả ngày.\n\nPhân cực\nGiảm chói, tăng độ nét và bảo vệ mắt khỏi bề mặt phản chiếu.\n\nLái xe\nTăng độ tương phản để lái xe an toàn hơn.\n\nMàu nhuộm\nGiảm độ chói và mang lại độ rõ nét tốt hơn trong nhiều điều kiện ánh sáng.',
80,NOW()),
(1,'Kính cận Vision BlueShield','Vision',1750000,25,
'Thông tin sản phẩm\nChất liệu: Nhựa dẻo + Kim loại\nThương hiệu: Vision\nKích thước: 52-18-140\nTrọng lượng nhẹ, đeo lâu không đau tai',
'Bao gồm\nBảo hành 365 ngày\nĐổi trả trong 30 ngày\nTặng hộp đựng + khăn lau + Nước lau kính',
'Mô tả sản phẩm\nKính Vision BlueShield, bảo vệ mắt khỏi ánh sáng xanh, TR90 nhẹ nhàng, dễ đeo lâu.',
'Giao hàng từ 2–5 ngày tùy khu vực. Hỗ trợ đổi trả trong vòng 30 ngày.',
'Chi tiết sản phẩm\nMã sản phẩm: VB548130-06\nCân nặng: 19.1g\nHình dạng: Quảng trường\nChiều rộng khung: 131mm\nKích cỡ: Trung bình\nPhù hợp khuôn mặt: Phổ biến\nVật liệu: TR90\nChiều rộng ống kính: 54mm\nChiều cao ống kính: 45mm\nChiều dài càng: 143mm',
'Chặn ánh sáng xanh\nGiảm mỏi mắt và bảo vệ mắt khỏi ánh sáng xanh có hại từ màn hình & thiết bị kỹ thuật số.\n\nQuang sắc\nTự động điều chỉnh theo ánh sáng, mang lại sự thoải mái cả ngày.\n\nPhân cực\nGiảm chói, tăng độ nét và bảo vệ mắt khỏi bề mặt phản chiếu.\n\nLái xe\nTăng độ tương phản để lái xe an toàn hơn.\n\nMàu nhuộm\nGiảm độ chói và mang lại độ rõ nét tốt hơn trong nhiều điều kiện ánh sáng.',
65,NOW()),
(1,'Kính cận Teen Năng Động Style','TeenStyle',850000,70,
'Thông tin sản phẩm\nChất liệu: Nhựa dẻo + Kim loại\nThương hiệu: TeenStyle\nKích thước: 52-18-140\nTrọng lượng nhẹ, đeo lâu không đau tai',
'Bao gồm\nBảo hành 365 ngày\nĐổi trả trong 30 ngày\nTặng hộp đựng + khăn lau + Nước lau kính',
'Mô tả sản phẩm\nKính TeenStyle năng động, TR90 nhẹ, phù hợp học sinh và sinh viên. Thiết kế trẻ trung, thoải mái đeo lâu.',
'Giao hàng từ 2–5 ngày tùy khu vực. Hỗ trợ đổi trả trong vòng 30 ngày.',
'Chi tiết sản phẩm\nMã sản phẩm: TN548130-07\nCân nặng: 19.1g\nHình dạng: Quảng trường\nChiều rộng khung: 131mm\nKích cỡ: Trung bình\nPhù hợp khuôn mặt: Phổ biến\nVật liệu: TR90\nChiều rộng ống kính: 54mm\nChiều cao ống kính: 45mm\nChiều dài càng: 143mm',
'Chặn ánh sáng xanh\nGiảm mỏi mắt và bảo vệ mắt khỏi ánh sáng xanh có hại từ màn hình & thiết bị kỹ thuật số.\n\nQuang sắc\nTự động điều chỉnh theo ánh sáng, mang lại sự thoải mái cả ngày.\n\nPhân cực\nGiảm chói, tăng độ nét và bảo vệ mắt khỏi bề mặt phản chiếu.\n\nLái xe\nTăng độ tương phản để lái xe an toàn hơn.\n\nMàu nhuộm\nGiảm độ chói và mang lại độ rõ nét tốt hơn trong nhiều điều kiện ánh sáng.',
200,NOW()),
(1,'Kính cận Teen Học Đường Smart','TeenStyle',880000,65,
'Thông tin sản phẩm\nChất liệu: Nhựa dẻo + Kim loại\nThương hiệu: TeenStyle\nKích thước: 52-18-140\nTrọng lượng nhẹ, đeo lâu không đau tai',
'Bao gồm\nBảo hành 365 ngày\nĐổi trả trong 30 ngày\nTặng hộp đựng + khăn lau + Nước lau kính',
'Mô tả sản phẩm\nKính TeenStyle Smart, thiết kế trẻ trung, TR90 nhẹ, phù hợp học sinh. Êm mắt, đeo lâu không mỏi.',
'Giao hàng từ 2–5 ngày tùy khu vực. Hỗ trợ đổi trả trong vòng 30 ngày.',
'Chi tiết sản phẩm\nMã sản phẩm: TS548130-08\nCân nặng: 19.1g\nHình dạng: Quảng trường\nChiều rộng khung: 131mm\nKích cỡ: Trung bình\nPhù hợp khuôn mặt: Phổ biến\nVật liệu: TR90\nChiều rộng ống kính: 54mm\nChiều cao ống kính: 45mm\nChiều dài càng: 143mm',
'Chặn ánh sáng xanh\nGiảm mỏi mắt và bảo vệ mắt khỏi ánh sáng xanh có hại từ màn hình & thiết bị kỹ thuật số.\n\nQuang sắc\nTự động điều chỉnh theo ánh sáng, mang lại sự thoải mái cả ngày.\n\nPhân cực\nGiảm chói, tăng độ nét và bảo vệ mắt khỏi bề mặt phản chiếu.\n\nLái xe\nTăng độ tương phản để lái xe an toàn hơn.\n\nMàu nhuộm\nGiảm độ chói và mang lại độ rõ nét tốt hơn trong nhiều điều kiện ánh sáng.',
180,NOW()),
(1,'Kính cận Văn Phòng Office Pro','Office',1400000,45,
'Thông tin sản phẩm\nChất liệu: Nhựa dẻo + Kim loại\nThương hiệu: Office\nKích thước: 52-18-140\nTrọng lượng nhẹ, đeo lâu không đau tai',
'Bao gồm\nBảo hành 365 ngày\nĐổi trả trong 30 ngày\nTặng hộp đựng + khăn lau + Nước lau kính',
'Mô tả sản phẩm\nKính Office Pro, TR90 cao cấp, thiết kế thanh lịch cho dân văn phòng. Nhẹ, thoải mái, phù hợp nhiều khuôn mặt.',
'Giao hàng từ 2–5 ngày tùy khu vực. Hỗ trợ đổi trả trong vòng 30 ngày.',
'Chi tiết sản phẩm\nMã sản phẩm: OFP548130-09\nCân nặng: 19.1g\nHình dạng: Quảng trường\nChiều rộng khung: 131mm\nKích cỡ: Trung bình\nPhù hợp khuôn mặt: Phổ biến\nVật liệu: TR90\nChiều rộng ống kính: 54mm\nChiều cao ống kính: 45mm\nChiều dài càng: 143mm',
'Chặn ánh sáng xanh\nGiảm mỏi mắt và bảo vệ mắt khỏi ánh sáng xanh có hại từ màn hình & thiết bị kỹ thuật số.\n\nQuang sắc\nTự động điều chỉnh theo ánh sáng, mang lại sự thoải mái cả ngày.\n\nPhân cực\nGiảm chói, tăng độ nét và bảo vệ mắt khỏi bề mặt phản chiếu.\n\nLái xe\nTăng độ tương phản để lái xe an toàn hơn.\n\nMàu nhuộm\nGiảm độ chói và mang lại độ rõ nét tốt hơn trong nhiều điều kiện ánh sáng.',
130,NOW()),
(1,'Kính cận Doanh Nhân Office Premium','Office',1450000,40,
'Thông tin sản phẩm\nChất liệu: Nhựa dẻo + Kim loại\nThương hiệu: Office\nKích thước: 52-18-140\nTrọng lượng nhẹ, đeo lâu không đau tai',
'Bao gồm\nBảo hành 365 ngày\nĐổi trả trong 30 ngày\nTặng hộp đựng + khăn lau + Nước lau kính',
'Mô tả sản phẩm\nKính Office Premium, thiết kế tinh tế cho doanh nhân. TR90 nhẹ nhàng, đeo lâu không mỏi, phù hợp nhiều khuôn mặt.',
'Giao hàng từ 2–5 ngày tùy khu vực. Hỗ trợ đổi trả trong vòng 30 ngày.',
'Chi tiết sản phẩm\nMã sản phẩm: OPP548130-10\nCân nặng: 19.1g\nHình dạng: Quảng trường\nChiều rộng khung: 131mm\nKích cỡ: Trung bình\nPhù hợp khuôn mặt: Phổ biến\nVật liệu: TR90\nChiều rộng ống kính: 54mm\nChiều cao ống kính: 45mm\nChiều dài càng: 143mm',
'Chặn ánh sáng xanh\nGiảm mỏi mắt và bảo vệ mắt khỏi ánh sáng xanh có hại từ màn hình & thiết bị kỹ thuật số.\n\nQuang sắc\nTự động điều chỉnh theo ánh sáng, mang lại sự thoải mái cả ngày.\n\nPhân cực\nGiảm chói, tăng độ nét và bảo vệ mắt khỏi bề mặt phản chiếu.\n\nLái xe\nTăng độ tương phản để lái xe an toàn hơn.\n\nMàu nhuộm\nGiảm độ chói và mang lại độ rõ nét tốt hơn trong nhiều điều kiện ánh sáng.',
125,NOW());

-- Kính mát 10 sản phẩm
INSERT INTO products
(category_id, product_name, brand, price, stock,
 short_infor_decription, short_guarantee_decription,
 general_description, shipping_info, product_details,
 glass_details, sold_quantity, created_at)
VALUES
(2,'Kính mát Đi Biển SunGo','SunGo',1100000,50,
'Thông tin sản phẩm\nChất liệu: Nhựa dẻo + Kim loại\nThương hiệu: SunGo\nKích thước: 55-17-140\nTrọng lượng nhẹ, đeo lâu không đau tai',
'Bao gồm\nBảo hành 365 ngày\nĐổi trả trong 30 ngày\nTặng hộp đựng + khăn lau + Nước lau kính',
'Mô tả sản phẩm\nKính mát SunGo đi biển, TR90 nhẹ, bảo vệ mắt khỏi ánh sáng mạnh. Thiết kế trẻ trung, phù hợp nhiều khuôn mặt.',
'Giao hàng từ 2–5 ngày tùy khu vực. Hỗ trợ đổi trả trong vòng 30 ngày.',
'Chi tiết sản phẩm\nMã sản phẩm: SG548230-01\nCân nặng: 20.0g\nHình dạng: Mắt mèo\nChiều rộng khung: 135mm\nKích cỡ: Trung bình\nPhù hợp khuôn mặt: Phổ biến\nVật liệu: TR90\nChiều rộng ống kính: 56mm\nChiều cao ống kính: 47mm\nChiều dài càng: 145mm',
'Chặn ánh sáng xanh\nGiảm mỏi mắt và bảo vệ mắt khỏi ánh sáng xanh có hại từ mặt trời và thiết bị kỹ thuật số.\n\nQuang sắc\nTự động điều chỉnh theo ánh sáng môi trường.\n\nPhân cực\nGiảm chói, tăng độ nét.\n\nLái xe\nTăng độ tương phản, an toàn khi lái xe.\n\nMàu nhuộm\nGiảm độ chói, giữ màu tự nhiên.',
90,NOW()),
(2,'Kính mát Chống UV SunGo','SunGo',1200000,45,
'Thông tin sản phẩm\nChất liệu: Nhựa dẻo + Kim loại\nThương hiệu: SunGo\nKích thước: 55-17-140\nTrọng lượng nhẹ, đeo lâu không đau tai',
'Bao gồm\nBảo hành 365 ngày\nĐổi trả trong 30 ngày\nTặng hộp đựng + khăn lau + Nước lau kính',
'Mô tả sản phẩm\nKính SunGo chống UV, TR90 nhẹ, bảo vệ mắt khỏi tia cực tím. Thiết kế trẻ trung, phù hợp mọi khuôn mặt.',
'Giao hàng từ 2–5 ngày tùy khu vực. Hỗ trợ đổi trả trong vòng 30 ngày.',
'Chi tiết sản phẩm\nMã sản phẩm: SGUV548230-02\nCân nặng: 20.0g\nHình dạng: Mắt mèo\nChiều rộng khung: 135mm\nKích cỡ: Trung bình\nPhù hợp khuôn mặt: Phổ biến\nVật liệu: TR90\nChiều rộng ống kính: 56mm\nChiều cao ống kính: 47mm\nChiều dài càng: 145mm',
'Chặn ánh sáng xanh\nGiảm mỏi mắt và bảo vệ mắt khỏi ánh sáng xanh có hại từ mặt trời và thiết bị kỹ thuật số.\n\nQuang sắc\nTự động điều chỉnh theo ánh sáng môi trường.\n\nPhân cực\nGiảm chói, tăng độ nét.\n\nLái xe\nTăng độ tương phản, an toàn khi lái xe.\n\nMàu nhuộm\nGiảm độ chói, giữ màu tự nhiên.',
85,NOW()),
(2,'Kính mát Ray Phong Cách Ý','Ray',1800000,30,
'Thông tin sản phẩm\nChất liệu: Nhựa dẻo + Kim loại\nThương hiệu: Ray\nKích thước: 55-17-140\nTrọng lượng nhẹ, đeo lâu không đau tai',
'Bao gồm\nBảo hành 365 ngày\nĐổi trả trong 30 ngày\nTặng hộp đựng + khăn lau + Nước lau kính',
'Mô tả sản phẩm\nKính Ray phong cách Ý, TR90 cao cấp, thiết kế sang trọng, bảo vệ mắt tối đa. Phù hợp nhiều khuôn mặt.',
'Giao hàng từ 2–5 ngày tùy khu vực. Hỗ trợ đổi trả trong vòng 30 ngày.',
'Chi tiết sản phẩm\nMã sản phẩm: RAY548230-03\nCân nặng: 21.0g\nHình dạng: Vuông\nChiều rộng khung: 138mm\nKích cỡ: Trung bình\nPhù hợp khuôn mặt: Phổ biến\nVật liệu: TR90\nChiều rộng ống kính: 58mm\nChiều cao ống kính: 48mm\nChiều dài càng: 146mm',
'Chặn ánh sáng xanh\nGiảm mỏi mắt và bảo vệ mắt khỏi ánh sáng xanh có hại từ mặt trời và thiết bị kỹ thuật số.\n\nQuang sắc\nTự động điều chỉnh theo ánh sáng môi trường.\n\nPhân cực\nGiảm chói, tăng độ nét.\n\nLái xe\nTăng độ tương phản, an toàn khi lái xe.\n\nMàu nhuộm\nGiảm độ chói, giữ màu tự nhiên.',
70,NOW()),
(2,'Kính mát Ray Sang Trọng','Ray',1900000,25,
'Thông tin sản phẩm\nChất liệu: Nhựa dẻo + Kim loại\nThương hiệu: Ray\nKích thước: 55-17-140\nTrọng lượng nhẹ, đeo lâu không đau tai',
'Bao gồm\nBảo hành 365 ngày\nĐổi trả trong 30 ngày\nTặng hộp đựng + khăn lau + Nước lau kính',
'Mô tả sản phẩm\nKính Ray sang trọng, TR90 cao cấp, bảo vệ mắt toàn diện. Thiết kế tinh tế, phù hợp nhiều khuôn mặt.',
'Giao hàng từ 2–5 ngày tùy khu vực. Hỗ trợ đổi trả trong vòng 30 ngày.',
'Chi tiết sản phẩm\nMã sản phẩm: RAYS548230-04\nCân nặng: 21.0g\nHình dạng: Vuông\nChiều rộng khung: 138mm\nKích cỡ: Trung bình\nPhù hợp khuôn mặt: Phổ biến\nVật liệu: TR90\nChiều rộng ống kính: 58mm\nChiều cao ống kính: 48mm\nChiều dài càng: 146mm',
'Chặn ánh sáng xanh\nGiảm mỏi mắt và bảo vệ mắt khỏi ánh sáng xanh có hại từ mặt trời và thiết bị kỹ thuật số.\n\nQuang sắc\nTự động điều chỉnh theo ánh sáng môi trường.\n\nPhân cực\nGiảm chói, tăng độ nét.\n\nLái xe\nTăng độ tương phản, an toàn khi lái xe.\n\nMàu nhuộm\nGiảm độ chói, giữ màu tự nhiên.',
65,NOW()),
(2,'Kính mát Thể Thao Sport Active','Sporty',950000,60,
'Thông tin sản phẩm\nChất liệu: Nhựa dẻo + Kim loại\nThương hiệu: Sporty\nKích thước: 55-17-140\nTrọng lượng nhẹ, đeo lâu không đau tai',
'Bao gồm\nBảo hành 365 ngày\nĐổi trả trong 30 ngày\nTặng hộp đựng + khăn lau + Nước lau kính',
'Mô tả sản phẩm\nKính Sporty Active, TR90 nhẹ, phù hợp vận động ngoài trời. Thiết kế năng động, bảo vệ mắt tối đa.',
'Giao hàng từ 2–5 ngày tùy khu vực. Hỗ trợ đổi trả trong vòng 30 ngày.',
'Chi tiết sản phẩm\nMã sản phẩm: SPA548230-05\nCân nặng: 20.5g\nHình dạng: Thể thao\nChiều rộng khung: 137mm\nKích cỡ: Trung bình\nPhù hợp khuôn mặt: Phổ biến\nVật liệu: TR90\nChiều rộng ống kính: 57mm\nChiều cao ống kính: 47mm\nChiều dài càng: 147mm',
'Chặn ánh sáng xanh\nGiảm mỏi mắt và bảo vệ mắt khỏi ánh sáng xanh có hại từ mặt trời và thiết bị kỹ thuật số.\n\nQuang sắc\nTự động điều chỉnh theo ánh sáng môi trường.\n\nPhân cực\nGiảm chói, tăng độ nét.\n\nLái xe\nTăng độ tương phản, an toàn khi lái xe.\n\nMàu nhuộm\nGiảm độ chói, giữ màu tự nhiên.',
120,NOW()),
(2,'Kính mát Dã Ngoại Sport Outdoor','Sporty',980000,55,
'Thông tin sản phẩm\nChất liệu: Nhựa dẻo + Kim loại\nThương hiệu: Sporty\nKích thước: 55-17-140\nTrọng lượng nhẹ, đeo lâu không đau tai',
'Bao gồm\nBảo hành 365 ngày\nĐổi trả trong 30 ngày\nTặng hộp đựng + khăn lau + Nước lau kính',
'Mô tả sản phẩm\nKính Sporty Outdoor, TR90 nhẹ, chống tia UV, phù hợp leo núi và chạy bộ.',
'Giao hàng từ 2–5 ngày tùy khu vực. Hỗ trợ đổi trả trong vòng 30 ngày.',
'Chi tiết sản phẩm\nMã sản phẩm: SPO548230-06\nCân nặng: 20.5g\nHình dạng: Thể thao\nChiều rộng khung: 137mm\nKích cỡ: Trung bình\nPhù hợp khuôn mặt: Phổ biến\nVật liệu: TR90\nChiều rộng ống kính: 57mm\nChiều cao ống kính: 47mm\nChiều dài càng: 147mm',
'Chặn ánh sáng xanh\nGiảm mỏi mắt và bảo vệ mắt khỏi ánh sáng xanh có hại từ mặt trời và thiết bị kỹ thuật số.\n\nQuang sắc\nTự động điều chỉnh theo ánh sáng môi trường.\n\nPhân cực\nGiảm chói, tăng độ nét.\n\nLái xe\nTăng độ tương phản, an toàn khi lái xe.\n\nMàu nhuộm\nGiảm độ chói, giữ màu tự nhiên.',
110,NOW()),
(2,'Kính mát Thời Trang Hàn Fashion','FashionX',1500000,40,
'Thông tin sản phẩm\nChất liệu: Nhựa dẻo + Kim loại\nThương hiệu: FashionX\nKích thước: 55-17-140\nTrọng lượng nhẹ, đeo lâu không đau tai',
'Bao gồm\nBảo hành 365 ngày\nĐổi trả trong 30 ngày\nTặng hộp đựng + khăn lau + Nước lau kính',
'Mô tả sản phẩm\nKính FashionX Hàn Quốc, TR90 nhẹ, phong cách sành điệu, phù hợp nhiều khuôn mặt.',
'Giao hàng từ 2–5 ngày tùy khu vực. Hỗ trợ đổi trả trong vòng 30 ngày.',
'Chi tiết sản phẩm\nMã sản phẩm: FH548230-07\nCân nặng: 20.0g\nHình dạng: Vuông\nChiều rộng khung: 136mm\nKích cỡ: Trung bình\nPhù hợp khuôn mặt: Phổ biến\nVật liệu: TR90\nChiều rộng ống kính: 57mm\nChiều cao ống kính: 47mm\nChiều dài càng: 146mm',
'Chặn ánh sáng xanh\nGiảm mỏi mắt và bảo vệ mắt khỏi ánh sáng xanh có hại từ mặt trời và thiết bị kỹ thuật số.\n\nQuang sắc\nTự động điều chỉnh theo ánh sáng môi trường.\n\nPhân cực\nGiảm chói, tăng độ nét.\n\nLái xe\nTăng độ tương phản, an toàn khi lái xe.\n\nMàu nhuộm\nGiảm độ chói, giữ màu tự nhiên.',
100,NOW()),
(2,'Kính mát Street Style Fashion','FashionX',1550000,35,
'Thông tin sản phẩm\nChất liệu: Nhựa dẻo + Kim loại\nThương hiệu: FashionX\nKích thước: 55-17-140\nTrọng lượng nhẹ, đeo lâu không đau tai',
'Bao gồm\nBảo hành 365 ngày\nĐổi trả trong 30 ngày\nTặng hộp đựng + khăn lau + Nước lau kính',
'Mô tả sản phẩm\nKính FashionX Street Style, TR90 nhẹ, phong cách trẻ trung đường phố.',
'Giao hàng từ 2–5 ngày tùy khu vực. Hỗ trợ đổi trả trong vòng 30 ngày.',
'Chi tiết sản phẩm\nMã sản phẩm: FSS548230-08\nCân nặng: 20.0g\nHình dạng: Vuông\nChiều rộng khung: 136mm\nKích cỡ: Trung bình\nPhù hợp khuôn mặt: Phổ biến\nVật liệu: TR90\nChiều rộng ống kính: 57mm\nChiều cao ống kính: 47mm\nChiều dài càng: 146mm',
'Chặn ánh sáng xanh\nGiảm mỏi mắt và bảo vệ mắt khỏi ánh sáng xanh có hại từ mặt trời và thiết bị kỹ thuật số.\n\nQuang sắc\nTự động điều chỉnh theo ánh sáng môi trường.\n\nPhân cực\nGiảm chói, tăng độ nét.\n\nLái xe\nTăng độ tương phản, an toàn khi lái xe.\n\nMàu nhuộm\nGiảm độ chói, giữ màu tự nhiên.',
95,NOW()),
(2,'Kính mát Retro Hoài Cổ','Retro',1300000,45,
'Thông tin sản phẩm\nChất liệu: Nhựa dẻo + Kim loại\nThương hiệu: Retro\nKích thước: 55-17-140\nTrọng lượng nhẹ, đeo lâu không đau tai',
'Bao gồm\nBảo hành 365 ngày\nĐổi trả trong 30 ngày\nTặng hộp đựng + khăn lau + Nước lau kính',
'Mô tả sản phẩm\nKính Retro cổ điển, TR90 nhẹ, phong cách hoài cổ, phù hợp nhiều khuôn mặt.',
'Giao hàng từ 2–5 ngày tùy khu vực. Hỗ trợ đổi trả trong vòng 30 ngày.',
'Chi tiết sản phẩm\nMã sản phẩm: RHC548230-09\nCân nặng: 21.0g\nHình dạng: Tròn\nChiều rộng khung: 137mm\nKích cỡ: Trung bình\nPhù hợp khuôn mặt: Phổ biến\nVật liệu: TR90\nChiều rộng ống kính: 57mm\nChiều cao ống kính: 47mm\nChiều dài càng: 147mm',
'Chặn ánh sáng xanh\nGiảm mỏi mắt và bảo vệ mắt khỏi ánh sáng xanh có hại từ mặt trời và thiết bị kỹ thuật số.\n\nQuang sắc\nTự động điều chỉnh theo ánh sáng môi trường.\n\nPhân cực\nGiảm chói, tăng độ nét.\n\nLái xe\nTăng độ tương phản, an toàn khi lái xe.\n\nMàu nhuộm\nGiảm độ chói, giữ màu tự nhiên.',
105,NOW()),
(2,'Kính mát Retro Old Style','Retro',1350000,40,
'Thông tin sản phẩm\nChất liệu: Nhựa dẻo + Kim loại\nThương hiệu: Retro\nKích thước: 55-17-140\nTrọng lượng nhẹ, đeo lâu không đau tai',
'Bao gồm\nBảo hành 365 ngày\nĐổi trả trong 30 ngày\nTặng hộp đựng + khăn lau + Nước lau kính',
'Mô tả sản phẩm\nKính Retro Old Style, TR90 nhẹ, phong cách vintage, phù hợp nhiều khuôn mặt.',
'Giao hàng từ 2–5 ngày tùy khu vực. Hỗ trợ đổi trả trong vòng 30 ngày.',
'Chi tiết sản phẩm\nMã sản phẩm: ROV548230-10\nCân nặng: 21.0g\nHình dạng: Tròn\nChiều rộng khung: 137mm\nKích cỡ: Trung bình\nPhù hợp khuôn mặt: Phổ biến\nVật liệu: TR90\nChiều rộng ống kính: 57mm\nChiều cao ống kính: 47mm\nChiều dài càng: 147mm',
'Chặn ánh sáng xanh\nGiảm mỏi mắt và bảo vệ mắt khỏi ánh sáng xanh có hại từ mặt trời và thiết bị kỹ thuật số.\n\nQuang sắc\nTự động điều chỉnh theo ánh sáng môi trường.\n\nPhân cực\nGiảm chói, tăng độ nét.\n\nLái xe\nTăng độ tương phản, an toàn khi lái xe.\n\nMàu nhuộm\nGiảm độ chói, giữ màu tự nhiên.',
98,NOW());

-- Kính áp tròng 10 sản phẩm
INSERT INTO products
(category_id, product_name, brand, price, stock,
 short_infor_decription, short_guarantee_decription,
 general_description, shipping_info, product_details,
 glass_details, sold_quantity, created_at)
VALUES
(3,'Kính áp tròng Màu Nâu Natural','OptiColor',500000,100,
'Thông tin sản phẩm\nChất liệu: Hydrogel cao cấp\nThương hiệu: OptiColor\nĐường kính: 14.2mm\nĐeo êm, thoải mái cả ngày',
'Bao gồm\nBảo hành 365 ngày\nĐổi trả trong 30 ngày\nTặng hộp đựng + dung dịch vệ sinh',
'Mô tả sản phẩm\nKính áp tròng OptiColor Nâu tự nhiên, mềm mại, dễ đeo, tạo màu mắt dịu dàng và tự nhiên.',
'Giao hàng từ 2–5 ngày tùy khu vực. Hỗ trợ đổi trả trong vòng 30 ngày.',
'Chi tiết sản phẩm\nMã sản phẩm: OC548330-01\nĐường kính: 14.2mm\nĐộ cong: 8.6mm\nHàm lượng nước: 55%\nSử dụng: Hàng ngày\nMàu sắc: Nâu tự nhiên',
'Chặn ánh sáng xanh\nGiảm mỏi mắt và bảo vệ mắt khi sử dụng thiết bị kỹ thuật số.\n\nPhân cực\nTăng độ rõ nét của màu mắt.\n\nThời gian đeo\nHàng ngày, tối đa 8 giờ/ngày.',
200,NOW()),
(3,'Kính áp tròng Xanh Dương Aqua','OptiColor',520000,95,
'Thông tin sản phẩm\nChất liệu: Hydrogel cao cấp\nThương hiệu: OptiColor\nĐường kính: 14.2mm\nĐeo êm, thoải mái cả ngày',
'Bao gồm\nBảo hành 365 ngày\nĐổi trả trong 30 ngày\nTặng hộp đựng + dung dịch vệ sinh',
'Mô tả sản phẩm\nKính áp tròng OptiColor Xanh Dương Aqua, mềm mại, tạo màu mắt tươi sáng và tự nhiên.',
'Giao hàng từ 2–5 ngày tùy khu vực. Hỗ trợ đổi trả trong vòng 30 ngày.',
'Chi tiết sản phẩm\nMã sản phẩm: OC548330-02\nĐường kính: 14.2mm\nĐộ cong: 8.6mm\nHàm lượng nước: 55%\nSử dụng: Hàng ngày\nMàu sắc: Xanh dương',
'Chặn ánh sáng xanh\nGiảm mỏi mắt và bảo vệ mắt khi sử dụng thiết bị kỹ thuật số.\n\nPhân cực\nTăng độ rõ nét của màu mắt.\n\nThời gian đeo\nHàng ngày, tối đa 8 giờ/ngày.',
180,NOW()),
(3,'Kính áp tròng Xám Grey Soft','OptiColor',480000,110,
'Thông tin sản phẩm\nChất liệu: Hydrogel cao cấp\nThương hiệu: OptiColor\nĐường kính: 14.2mm\nĐeo êm, thoải mái cả ngày',
'Bao gồm\nBảo hành 365 ngày\nĐổi trả trong 30 ngày\nTặng hộp đựng + dung dịch vệ sinh',
'Mô tả sản phẩm\nKính áp tròng OptiColor Xám Grey Soft, tạo màu mắt tự nhiên, mềm mại, dễ đeo.',
'Giao hàng từ 2–5 ngày tùy khu vực. Hỗ trợ đổi trả trong vòng 30 ngày.',
'Chi tiết sản phẩm\nMã sản phẩm: OC548330-03\nĐường kính: 14.2mm\nĐộ cong: 8.6mm\nHàm lượng nước: 55%\nSử dụng: Hàng ngày\nMàu sắc: Xám',
'Chặn ánh sáng xanh\nGiảm mỏi mắt và bảo vệ mắt khi sử dụng thiết bị kỹ thuật số.\n\nPhân cực\nTăng độ rõ nét của màu mắt.\n\nThời gian đeo\nHàng ngày, tối đa 8 giờ/ngày.',
160,NOW()),
(3,'Kính áp tròng Tím Violet Lux','OptiColor',550000,90,
'Thông tin sản phẩm\nChất liệu: Hydrogel cao cấp\nThương hiệu: OptiColor\nĐường kính: 14.2mm\nĐeo êm, thoải mái cả ngày',
'Bao gồm\nBảo hành 365 ngày\nĐổi trả trong 30 ngày\nTặng hộp đựng + dung dịch vệ sinh',
'Mô tả sản phẩm\nKính áp tròng Violet Lux, tạo màu mắt độc đáo, mềm mại và an toàn cho mắt.',
'Giao hàng từ 2–5 ngày tùy khu vực. Hỗ trợ đổi trả trong vòng 30 ngày.',
'Chi tiết sản phẩm\nMã sản phẩm: OC548330-04\nĐường kính: 14.2mm\nĐộ cong: 8.6mm\nHàm lượng nước: 55%\nSử dụng: Hàng ngày\nMàu sắc: Tím',
'Chặn ánh sáng xanh\nGiảm mỏi mắt và bảo vệ mắt khi sử dụng thiết bị kỹ thuật số.\n\nPhân cực\nTăng độ rõ nét của màu mắt.\n\nThời gian đeo\nHàng ngày, tối đa 8 giờ/ngày.',
140,NOW()),
(3,'Kính áp tròng Nâu Socola Elegant','OptiColor',500000,105,
'Thông tin sản phẩm\nChất liệu: Hydrogel cao cấp\nThương hiệu: OptiColor\nĐường kính: 14.2mm\nĐeo êm, thoải mái cả ngày',
'Bao gồm\nBảo hành 365 ngày\nĐổi trả trong 30 ngày\nTặng hộp đựng + dung dịch vệ sinh',
'Mô tả sản phẩm\nKính Socola Elegant, tạo mắt nâu tự nhiên, mềm mại, đeo lâu không mỏi.',
'Giao hàng từ 2–5 ngày tùy khu vực. Hỗ trợ đổi trả trong vòng 30 ngày.',
'Chi tiết sản phẩm\nMã sản phẩm: OC548330-05\nĐường kính: 14.2mm\nĐộ cong: 8.6mm\nHàm lượng nước: 55%\nSử dụng: Hàng ngày\nMàu sắc: Nâu Socola',
'Chặn ánh sáng xanh\nGiảm mỏi mắt và bảo vệ mắt khi sử dụng thiết bị kỹ thuật số.\n\nPhân cực\nTăng độ rõ nét của màu mắt.\n\nThời gian đeo\nHàng ngày, tối đa 8 giờ/ngày.',
120,NOW()),
(3,'Kính áp tròng Xanh Lá Leaf Fresh','OptiColor',520000,95,
'Thông tin sản phẩm\nChất liệu: Hydrogel cao cấp\nThương hiệu: OptiColor\nĐường kính: 14.2mm\nĐeo êm, thoải mái cả ngày',
'Bao gồm\nBảo hành 365 ngày\nĐổi trả trong 30 ngày\nTặng hộp đựng + dung dịch vệ sinh',
'Mô tả sản phẩm\nKính Leaf Fresh, mắt xanh tự nhiên, mềm mại, bảo vệ mắt tối ưu.',
'Giao hàng từ 2–5 ngày tùy khu vực. Hỗ trợ đổi trả trong vòng 30 ngày.',
'Chi tiết sản phẩm\nMã sản phẩm: OC548330-06\nĐường kính: 14.2mm\nĐộ cong: 8.6mm\nHàm lượng nước: 55%\nSử dụng: Hàng ngày\nMàu sắc: Xanh Lá',
'Chặn ánh sáng xanh\nGiảm mỏi mắt và bảo vệ mắt khi sử dụng thiết bị kỹ thuật số.\n\nPhân cực\nTăng độ rõ nét của màu mắt.\n\nThời gian đeo\nHàng ngày, tối đa 8 giờ/ngày.',
110,NOW()),
(3,'Kính áp tròng Xanh Biển Ocean Blue','OptiColor',530000,90,
'Thông tin sản phẩm\nChất liệu: Hydrogel cao cấp\nThương hiệu: OptiColor\nĐường kính: 14.2mm\nĐeo êm, thoải mái cả ngày',
'Bao gồm\nBảo hành 365 ngày\nĐổi trả trong 30 ngày\nTặng hộp đựng + dung dịch vệ sinh',
'Mô tả sản phẩm\nKính Ocean Blue, mắt xanh biển tự nhiên, mềm mại, dễ đeo cả ngày.',
'Giao hàng từ 2–5 ngày tùy khu vực. Hỗ trợ đổi trả trong vòng 30 ngày.',
'Chi tiết sản phẩm\nMã sản phẩm: OC548330-07\nĐường kính: 14.2mm\nĐộ cong: 8.6mm\nHàm lượng nước: 55%\nSử dụng: Hàng ngày\nMàu sắc: Xanh Biển',
'Chặn ánh sáng xanh\nGiảm mỏi mắt và bảo vệ mắt khi sử dụng thiết bị kỹ thuật số.\n\nPhân cực\nTăng độ rõ nét của màu mắt.\n\nThời gian đeo\nHàng ngày, tối đa 8 giờ/ngày.',
100,NOW()),
(3,'Kính áp tròng Hồng Pinky Charm','OptiColor',510000,95,
'Thông tin sản phẩm\nChất liệu: Hydrogel cao cấp\nThương hiệu: OptiColor\nĐường kính: 14.2mm\nĐeo êm, thoải mái cả ngày',
'Bao gồm\nBảo hành 365 ngày\nĐổi trả trong 30 ngày\nTặng hộp đựng + dung dịch vệ sinh',
'Mô tả sản phẩm\nKính Pinky Charm, mắt hồng ngọt ngào, mềm mại, phù hợp phong cách dễ thương.',
'Giao hàng từ 2–5 ngày tùy khu vực. Hỗ trợ đổi trả trong vòng 30 ngày.',
'Chi tiết sản phẩm\nMã sản phẩm: OC548330-08\nĐường kính: 14.2mm\nĐộ cong: 8.6mm\nHàm lượng nước: 55%\nSử dụng: Hàng ngày\nMàu sắc: Hồng',
'Chặn ánh sáng xanh\nGiảm mỏi mắt và bảo vệ mắt khi sử dụng thiết bị kỹ thuật số.\n\nPhân cực\nTăng độ rõ nét của màu mắt.\n\nThời gian đeo\nHàng ngày, tối đa 8 giờ/ngày.',
90,NOW()),
(3,'Kính áp tròng Đen Night Shadow','OptiColor',500000,100,
'Thông tin sản phẩm\nChất liệu: Hydrogel cao cấp\nThương hiệu: OptiColor\nĐường kính: 14.2mm\nĐeo êm, thoải mái cả ngày',
'Bao gồm\nBảo hành 365 ngày\nĐổi trả trong 30 ngày\nTặng hộp đựng + dung dịch vệ sinh',
'Mô tả sản phẩm\nKính Night Shadow, mắt đen huyền bí, mềm mại, dễ đeo cả ngày.',
'Giao hàng từ 2–5 ngày tùy khu vực. Hỗ trợ đổi trả trong vòng 30 ngày.',
'Chi tiết sản phẩm\nMã sản phẩm: OC548330-09\nĐường kính: 14.2mm\nĐộ cong: 8.6mm\nHàm lượng nước: 55%\nSử dụng: Hàng ngày\nMàu sắc: Đen',
'Chặn ánh sáng xanh\nGiảm mỏi mắt và bảo vệ mắt khi sử dụng thiết bị kỹ thuật số.\n\nPhân cực\nTăng độ rõ nét của màu mắt.\n\nThời gian đeo\nHàng ngày, tối đa 8 giờ/ngày.',
85,NOW()),
(3,'Kính áp tròng Xám Light Grey','OptiColor',480000,110,
'Thông tin sản phẩm\nChất liệu: Hydrogel cao cấp\nThương hiệu: OptiColor\nĐường kính: 14.2mm\nĐeo êm, thoải mái cả ngày',
'Bao gồm\nBảo hành 365 ngày\nĐổi trả trong 30 ngày\nTặng hộp đựng + dung dịch vệ sinh',
'Mô tả sản phẩm\nKính Light Grey, mắt xám nhạt tự nhiên, mềm mại, dễ đeo cả ngày.',
'Giao hàng từ 2–5 ngày tùy khu vực. Hỗ trợ đổi trả trong vòng 30 ngày.',
'Chi tiết sản phẩm\nMã sản phẩm: OC548330-10\nĐường kính: 14.2mm\nĐộ cong: 8.6mm\nHàm lượng nước: 55%\nSử dụng: Hàng ngày\nMàu sắc: Xám Nhạt',
'Chặn ánh sáng xanh\nGiảm mỏi mắt và bảo vệ mắt khi sử dụng thiết bị kỹ thuật số.\n\nPhân cực\nTăng độ rõ nét của màu mắt.\n\nThời gian đeo\nHàng ngày, tối đa 8 giờ/ngày.',
80,NOW());

-- Gọng kính 10 sản phẩm
INSERT INTO products
(category_id, product_name, brand, price, stock,
 short_infor_decription, short_guarantee_decription,
 general_description, shipping_info, product_details,
 glass_details, sold_quantity, created_at)
VALUES
(4,'Gọng kính Rodz Classic Đen','Rodz',700000,50,
'Thông tin sản phẩm\nChất liệu: Kim loại + TR90\nThương hiệu: Rodz\nKích thước: 52-18-140\nTrọng lượng nhẹ, đeo lâu không đau tai',
'Bao gồm\nBảo hành 365 ngày\nĐổi trả trong 30 ngày\nTặng hộp đựng + khăn lau',
'Mô tả sản phẩm\nGọng kính Rodz Classic đen, phong cách cổ điển, TR90 nhẹ, phù hợp nhiều khuôn mặt.',
'Giao hàng từ 2–5 ngày tùy khu vực. Hỗ trợ đổi trả trong vòng 30 ngày.',
'Chi tiết sản phẩm\nMã sản phẩm: RG548430-01\nCân nặng: 18.5g\nHình dạng: Vuông\nChiều rộng khung: 132mm\nKích cỡ: Trung bình\nPhù hợp khuôn mặt: Phổ biến\nVật liệu: TR90\nChiều dài càng: 144mm',
'Chặn ánh sáng xanh\nBảo vệ mắt khỏi ánh sáng xanh từ thiết bị kỹ thuật số.\n\nPhân cực\nGiảm chói, tăng độ nét.',
120,NOW()),
(4,'Gọng kính Rodz Thanh Lịch Nâu','Rodz',720000,45,
'Thông tin sản phẩm\nChất liệu: Kim loại + TR90\nThương hiệu: Rodz\nKích thước: 52-18-140\nTrọng lượng nhẹ, đeo lâu không đau tai',
'Bao gồm\nBảo hành 365 ngày\nĐổi trả trong 30 ngày\nTặng hộp đựng + khăn lau',
'Mô tả sản phẩm\nGọng kính Rodz nâu thanh lịch, TR90 nhẹ, thiết kế tinh tế, phù hợp văn phòng và học sinh.',
'Giao hàng từ 2–5 ngày tùy khu vực. Hỗ trợ đổi trả trong vòng 30 ngày.',
'Chi tiết sản phẩm\nMã sản phẩm: RG548430-02\nCân nặng: 18.5g\nHình dạng: Vuông\nChiều rộng khung: 132mm\nKích cỡ: Trung bình\nPhù hợp khuôn mặt: Phổ biến\nVật liệu: TR90\nChiều dài càng: 144mm',
'Chặn ánh sáng xanh\nBảo vệ mắt khỏi ánh sáng xanh từ thiết bị kỹ thuật số.\n\nPhân cực\nGiảm chói, tăng độ nét.',
110,NOW()),
(4,'Gọng kính Rodz Fashion Đỏ','Rodz',750000,40,
'Thông tin sản phẩm\nChất liệu: Kim loại + TR90\nThương hiệu: Rodz\nKích thước: 52-18-140\nTrọng lượng nhẹ, đeo lâu không đau tai',
'Bao gồm\nBảo hành 365 ngày\nĐổi trả trong 30 ngày\nTặng hộp đựng + khăn lau',
'Mô tả sản phẩm\nGọng kính Rodz đỏ nổi bật, TR90 nhẹ, phong cách thời trang, phù hợp nhiều khuôn mặt.',
'Giao hàng từ 2–5 ngày tùy khu vực. Hỗ trợ đổi trả trong vòng 30 ngày.',
'Chi tiết sản phẩm\nMã sản phẩm: RG548430-03\nCân nặng: 18.5g\nHình dạng: Vuông\nChiều rộng khung: 132mm\nKích cỡ: Trung bình\nPhù hợp khuôn mặt: Phổ biến\nVật liệu: TR90\nChiều dài càng: 144mm',
'Chặn ánh sáng xanh\nBảo vệ mắt khỏi ánh sáng xanh từ thiết bị kỹ thuật số.\n\nPhân cực\nGiảm chói, tăng độ nét.',
105,NOW()),
(4,'Gọng kính Rodz Năng Động Xanh','Rodz',730000,50,
'Thông tin sản phẩm\nChất liệu: Kim loại + TR90\nThương hiệu: Rodz\nKích thước: 52-18-140\nTrọng lượng nhẹ, đeo lâu không đau tai',
'Bao gồm\nBảo hành 365 ngày\nĐổi trả trong 30 ngày\nTặng hộp đựng + khăn lau',
'Mô tả sản phẩm\nGọng kính Rodz xanh năng động, TR90 nhẹ, phong cách trẻ trung, phù hợp học sinh và sinh viên.',
'Giao hàng từ 2–5 ngày tùy khu vực. Hỗ trợ đổi trả trong vòng 30 ngày.',
'Chi tiết sản phẩm\nMã sản phẩm: RG548430-04\nCân nặng: 18.5g\nHình dạng: Vuông\nChiều rộng khung: 132mm\nKích cỡ: Trung bình\nPhù hợp khuôn mặt: Phổ biến\nVật liệu: TR90\nChiều dài càng: 144mm',
'Chặn ánh sáng xanh\nBảo vệ mắt khỏi ánh sáng xanh từ thiết bị kỹ thuật số.\n\nPhân cực\nGiảm chói, tăng độ nét.',
95,NOW()),
(4,'Gọng kính Rodz Vintage Nâu','Rodz',710000,45,
'Thông tin sản phẩm\nChất liệu: Kim loại + TR90\nThương hiệu: Rodz\nKích thước: 52-18-140\nTrọng lượng nhẹ, đeo lâu không đau tai',
'Bao gồm\nBảo hành 365 ngày\nĐổi trả trong 30 ngày\nTặng hộp đựng + khăn lau',
'Mô tả sản phẩm\nGọng kính Rodz Vintage Nâu, TR90 nhẹ, phong cách cổ điển, phù hợp nhiều khuôn mặt.',
'Giao hàng từ 2–5 ngày tùy khu vực. Hỗ trợ đổi trả trong vòng 30 ngày.',
'Chi tiết sản phẩm\nMã sản phẩm: RG548430-05\nCân nặng: 18.5g\nHình dạng: Vuông\nChiều rộng khung: 132mm\nKích cỡ: Trung bình\nPhù hợp khuôn mặt: Phổ biến\nVật liệu: TR90\nChiều dài càng: 144mm',
'Chặn ánh sáng xanh\nBảo vệ mắt khỏi ánh sáng xanh từ thiết bị kỹ thuật số.\n\nPhân cực\nGiảm chói, tăng độ nét.',
90,NOW()),
(4,'Gọng kính Rodz Trẻ Trung Xám','Rodz',720000,50,
'Thông tin sản phẩm\nChất liệu: Kim loại + TR90\nThương hiệu: Rodz\nKích thước: 52-18-140\nTrọng lượng nhẹ, đeo lâu không đau tai',
'Bao gồm\nBảo hành 365 ngày\nĐổi trả trong 30 ngày\nTặng hộp đựng + khăn lau',
'Mô tả sản phẩm\nGọng kính Rodz Xám trẻ trung, TR90 nhẹ, phong cách năng động, phù hợp học sinh, sinh viên.',
'Giao hàng từ 2–5 ngày tùy khu vực. Hỗ trợ đổi trả trong vòng 30 ngày.',
'Chi tiết sản phẩm\nMã sản phẩm: RG548430-06\nCân nặng: 18.5g\nHình dạng: Vuông\nChiều rộng khung: 132mm\nKích cỡ: Trung bình\nPhù hợp khuôn mặt: Phổ biến\nVật liệu: TR90\nChiều dài càng: 144mm',
'Chặn ánh sáng xanh\nBảo vệ mắt khỏi ánh sáng xanh từ thiết bị kỹ thuật số.\n\nPhân cực\nGiảm chói, tăng độ nét.',
88,NOW()),
(4,'Gọng kính Rodz Thời Trang Hồng','Rodz',730000,40,
'Thông tin sản phẩm\nChất liệu: Kim loại + TR90\nThương hiệu: Rodz\nKích thước: 52-18-140\nTrọng lượng nhẹ, đeo lâu không đau tai',
'Bao gồm\nBảo hành 365 ngày\nĐổi trả trong 30 ngày\nTặng hộp đựng + khăn lau',
'Mô tả sản phẩm\nGọng kính Rodz Hồng thời trang, TR90 nhẹ, phong cách dễ thương, phù hợp nhiều khuôn mặt.',
'Giao hàng từ 2–5 ngày tùy khu vực. Hỗ trợ đổi trả trong vòng 30 ngày.',
'Chi tiết sản phẩm\nMã sản phẩm: RG548430-07\nCân nặng: 18.5g\nHình dạng: Vuông\nChiều rộng khung: 132mm\nKích cỡ: Trung bình\nPhù hợp khuôn mặt: Phổ biến\nVật liệu: TR90\nChiều dài càng: 144mm',
'Chặn ánh sáng xanh\nBảo vệ mắt khỏi ánh sáng xanh từ thiết bị kỹ thuật số.\n\nPhân cực\nGiảm chói, tăng độ nét.',
85,NOW()),
(4,'Gọng kính Rodz Năng Động Cam','Rodz',740000,35,
'Thông tin sản phẩm\nChất liệu: Kim loại + TR90\nThương hiệu: Rodz\nKích thước: 52-18-140\nTrọng lượng nhẹ, đeo lâu không đau tai',
'Bao gồm\nBảo hành 365 ngày\nĐổi trả trong 30 ngày\nTặng hộp đựng + khăn lau',
'Mô tả sản phẩm\nGọng kính Rodz Cam năng động, TR90 nhẹ, phong cách trẻ trung, phù hợp học sinh, sinh viên.',
'Giao hàng từ 2–5 ngày tùy khu vực. Hỗ trợ đổi trả trong vòng 30 ngày.',
'Chi tiết sản phẩm\nMã sản phẩm: RG548430-08\nCân nặng: 18.5g\nHình dạng: Vuông\nChiều rộng khung: 132mm\nKích cỡ: Trung bình\nPhù hợp khuôn mặt: Phổ biến\nVật liệu: TR90\nChiều dài càng: 144mm',
'Chặn ánh sáng xanh\nBảo vệ mắt khỏi ánh sáng xanh từ thiết bị kỹ thuật số.\n\nPhân cực\nGiảm chói, tăng độ nét.',
82,NOW()),
(4,'Gọng kính Rodz Sang Trọng Vàng','Rodz',780000,30,
'Thông tin sản phẩm\nChất liệu: Kim loại + TR90\nThương hiệu: Rodz\nKích thước: 52-18-140\nTrọng lượng nhẹ, đeo lâu không đau tai',
'Bao gồm\nBảo hành 365 ngày\nĐổi trả trong 30 ngày\nTặng hộp đựng + khăn lau',
'Mô tả sản phẩm\nGọng kính Rodz Vàng sang trọng, TR90 nhẹ, thiết kế tinh tế, phù hợp văn phòng và sự kiện.',
'Giao hàng từ 2–5 ngày tùy khu vực. Hỗ trợ đổi trả trong vòng 30 ngày.',
'Chi tiết sản phẩm\nMã sản phẩm: RG548430-09\nCân nặng: 18.5g\nHình dạng: Vuông\nChiều rộng khung: 132mm\nKích cỡ: Trung bình\nPhù hợp khuôn mặt: Phổ biến\nVật liệu: TR90\nChiều dài càng: 144mm',
'Chặn ánh sáng xanh\nBảo vệ mắt khỏi ánh sáng xanh từ thiết bị kỹ thuật số.\n\nPhân cực\nGiảm chói, tăng độ nét.',
80,NOW()),
(4,'Gọng kính Rodz Classic Trắng','Rodz',700000,50,
'Thông tin sản phẩm\nChất liệu: Kim loại + TR90\nThương hiệu: Rodz\nKích thước: 52-18-140\nTrọng lượng nhẹ, đeo lâu không đau tai',
'Bao gồm\nBảo hành 365 ngày\nĐổi trả trong 30 ngày\nTặng hộp đựng + khăn lau',
'Mô tả sản phẩm\nGọng kính Rodz Trắng Classic, TR90 nhẹ, phong cách thanh lịch, phù hợp nhiều khuôn mặt.',
'Giao hàng từ 2–5 ngày tùy khu vực. Hỗ trợ đổi trả trong vòng 30 ngày.',
'Chi tiết sản phẩm\nMã sản phẩm: RG548430-10\nCân nặng: 18.5g\nHình dạng: Vuông\nChiều rộng khung: 132mm\nKích cỡ: Trung bình\nPhù hợp khuôn mặt: Phổ biến\nVật liệu: TR90\nChiều dài càng: 144mm',
'Chặn ánh sáng xanh\nBảo vệ mắt khỏi ánh sáng xanh từ thiết bị kỹ thuật số.\n\nPhân cực\nGiảm chói, tăng độ nét.',
75,NOW());

